//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klijent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Klijent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107_1070273_green_background_vector_png_portable_network_graphics {
            get {
                object obj = ResourceManager.GetObject("107-1070273_green-background-vector-png-portable-network-graphics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10823229 {
            get {
                object obj = ResourceManager.GetObject("10823229", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10823229__1_ {
            get {
                object obj = ResourceManager.GetObject("10823229 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10823283 {
            get {
                object obj = ResourceManager.GetObject("10823283", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _144_1447919_transparent_corner_ribbon_png_corner_ribbon_png_transparente {
            get {
                object obj = ResourceManager.GetObject("144-1447919_transparent-corner-ribbon-png-corner-ribbon-png-transparente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15149351 {
            get {
                object obj = ResourceManager.GetObject("15149351", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1dsfafghjui765trgf {
            get {
                object obj = ResourceManager.GetObject("1dsfafghjui765trgf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20820851 {
            get {
                object obj = ResourceManager.GetObject("20820851", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23036781 {
            get {
                object obj = ResourceManager.GetObject("23036781", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _29273471 {
            get {
                object obj = ResourceManager.GetObject("29273471", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_559045209_BUVgSo6M60WPht0331vQaDyErt4PjUPk {
            get {
                object obj = ResourceManager.GetObject("360_F_559045209_BUVgSo6M60WPht0331vQaDyErt4PjUPk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_559045228_304NjxgJnNBUHdrO6hyhzxx11rpwAS7M__1_ {
            get {
                object obj = ResourceManager.GetObject("360_F_559045228_304NjxgJnNBUHdrO6hyhzxx11rpwAS7M (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_649088106_dNidCj4QMhNAavuXXluy7JLMbjtGPGHo {
            get {
                object obj = ResourceManager.GetObject("360_F_649088106_dNidCj4QMhNAavuXXluy7JLMbjtGPGHo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39673691 {
            get {
                object obj = ResourceManager.GetObject("39673691", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39673692 {
            get {
                object obj = ResourceManager.GetObject("39673692", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _66433621 {
            get {
                object obj = ResourceManager.GetObject("66433621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _76542441 {
            get {
                object obj = ResourceManager.GetObject("76542441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _780_7803978_cute_speech_bubble_png_cute_green_speech_bubbles {
            get {
                object obj = ResourceManager.GetObject("780-7803978_cute-speech-bubble-png-cute-green-speech-bubbles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _89_893814_green_clipart_speech_bubble_green_speech_bubble_icon {
            get {
                object obj = ResourceManager.GetObject("89-893814_green-clipart-speech-bubble-green-speech-bubble-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apple1 {
            get {
                object obj = ResourceManager.GetObject("apple1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cooking_border_with_cutlery_kitchen_utensils_hand_drawn_cutlery_place_for_text_vector_illustration_700_2151293845 {
            get {
                object obj = ResourceManager.GetObject("cooking-border-with-cutlery-kitchen-utensils-hand-drawn-cutlery-place-for-text-ve" +
                        "ctor-illustration-700-2151293845", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cooking_Recipe_PNG_Download_Image {
            get {
                object obj = ResourceManager.GetObject("Cooking-Recipe-PNG-Download-Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Corner_Banner_Green_PNG_Clipart {
            get {
                object obj = ResourceManager.GetObject("Corner_Banner_Green_PNG_Clipart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dd9dc9d83423bc037b511d73b29e6b801111111111111111 {
            get {
                object obj = ResourceManager.GetObject("dd9dc9d83423bc037b511d73b29e6b801111111111111111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ef49e2aaf893ef4a8a5e248db6930007 {
            get {
                object obj = ResourceManager.GetObject("ef49e2aaf893ef4a8a5e248db6930007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ezgif_7_2743d8bbbc {
            get {
                object obj = ResourceManager.GetObject("ezgif-7-2743d8bbbc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ezgif_7_2743d8bbbc1 {
            get {
                object obj = ResourceManager.GetObject("ezgif-7-2743d8bbbc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ezgif_7_466b35aa58 {
            get {
                object obj = ResourceManager.GetObject("ezgif-7-466b35aa58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ezgif_7_954f0694b5 {
            get {
                object obj = ResourceManager.GetObject("ezgif-7-954f0694b5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ezgif_7_ec4369be97 {
            get {
                object obj = ResourceManager.GetObject("ezgif-7-ec4369be97", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fashionable_business_card_design_5a3bcec5d5ed14_0890598015138689978763 {
            get {
                object obj = ResourceManager.GetObject("fashionable-business-card-design-5a3bcec5d5ed14.0890598015138689978763", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_exit_logout_icon_2861_thumb {
            get {
                object obj = ResourceManager.GetObject("free-exit-logout-icon-2861-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_green_apple_1 {
            get {
                object obj = ResourceManager.GetObject("free-green-apple-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap geometric_cute_citrus_fruit_seamless_pattern_isolated_fruits_endless_wallpaper_97843_4107 {
            get {
                object obj = ResourceManager.GetObject("geometric-cute-citrus-fruit-seamless-pattern-isolated-fruits-endless-wallpaper_97" +
                        "843-4107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_spoon_food_logo_E82A50964F_seeklogo_com {
            get {
                object obj = ResourceManager.GetObject("green-spoon-food-logo-E82A50964F-seeklogo.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green1 {
            get {
                object obj = ResourceManager.GetObject("green1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isolated_seamless_fruit_pattern_with_green_pastel_apple_silhouettes_white_background_healthy_food_print_vector {
            get {
                object obj = ResourceManager.GetObject("isolated-seamless-fruit-pattern-with-green-pastel-apple-silhouettes-white-backgro" +
                        "und-healthy-food-print-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isolated_seamless_fruit_pattern_with_green_pastel_apple_silhouettes_white_background_healthy_food_print_vector1 {
            get {
                object obj = ResourceManager.GetObject("isolated-seamless-fruit-pattern-with-green-pastel-apple-silhouettes-white-backgro" +
                        "und-healthy-food-print-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1339324933_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1339324933-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1339324933_612x6124 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1339324933-612x6124", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kitchen_tools_continuous_one_line_drawing_vector_32641276 {
            get {
                object obj = ResourceManager.GetObject("kitchen-tools-continuous-one-line-drawing-vector-32641276", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap narandzasti {
            get {
                object obj = ResourceManager.GetObject("narandzasti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap narandzasti__1_ {
            get {
                object obj = ResourceManager.GetObject("narandzasti (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__2_ {
            get {
                object obj = ResourceManager.GetObject("output-onlinepngtools (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza_23 {
            get {
                object obj = ResourceManager.GetObject("pizza-23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza_231 {
            get {
                object obj = ResourceManager.GetObject("pizza-231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza_232 {
            get {
                object obj = ResourceManager.GetObject("pizza-232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza_233 {
            get {
                object obj = ResourceManager.GetObject("pizza-233", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_fresh_and_stylish_background_green_lines_background_green_background_pictures_fresh {
            get {
                object obj = ResourceManager.GetObject("png-transparent-fresh-and-stylish-background-green-lines-background-green-backgro" +
                        "und-pictures-fresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_fast_food_logo_png_image_5763171 {
            get {
                object obj = ResourceManager.GetObject("pngtree-fast-food-logo-png-image_5763171", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_green_chat_bubble_icon_png_image_4754359 {
            get {
                object obj = ResourceManager.GetObject("pngtree-green-chat-bubble-icon-png-image_4754359", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_green_elegant_banner_frame_png_image_6590336 {
            get {
                object obj = ResourceManager.GetObject("pngtree-green-elegant-banner-frame-png-image_6590336", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap posters_fresh_pattern_with_lemons_full_fruits_and_slices_vitamin_background_seamless_vector_texture_jpg {
            get {
                object obj = ResourceManager.GetObject("posters-fresh-pattern-with-lemons-full-fruits-and-slices-vitamin-background-seaml" +
                        "ess-vector-texture.jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap posters_fresh_pattern_with_lemons_full_fruits_and_slices_vitamin_background_seamless_vector_texture1 {
            get {
                object obj = ResourceManager.GetObject("posters-fresh-pattern-with-lemons-full-fruits-and-slices-vitamin-background-seaml" +
                        "ess-vector-texture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roze {
            get {
                object obj = ResourceManager.GetObject("roze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seamless_pattern_of_baking_doodle_cooking_elements_mixer_butter_flour_spoon_whisk_in_sketch_style_hand_drawn_illustration_isolated_on_white_background_vector {
            get {
                object obj = ResourceManager.GetObject("seamless-pattern-of-baking-doodle-cooking-elements-mixer-butter-flour-spoon-whisk" +
                        "-in-sketch-style-hand-drawn-illustration-isolated-on-white-background-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seamless_pattern_of_baking_doodle_cooking_elements_mixer_butter_flour_spoon_whisk_in_sketch_style_hand_drawn_illustration_isolated_on_white_background_vector1 {
            get {
                object obj = ResourceManager.GetObject("seamless-pattern-of-baking-doodle-cooking-elements-mixer-butter-flour-spoon-whisk" +
                        "-in-sketch-style-hand-drawn-illustration-isolated-on-white-background-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zeleni {
            get {
                object obj = ResourceManager.GetObject("zeleni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
